In [58]:
# Imports
import torch
import numpy as np




In [ ]:
# Utils


class TextCorpus:

    _corpus: list
    _content: str 
    _trigrams: list[tuple[int, int, int]]

    stoi: dict[str, int] 

    def __init__(self, content: str) -> None:
        if not len(content) >= 3:
            raise ValueError()
        
        self._content = content
        self._trigrams = []
        
        self._build_corpus()

        
    def _build_corpus(self):
        self._corpus = sorted(list(set(self._content)))
        self.stoi = { t: i for i, t in enumerate(self._corpus)}

    @property
    def corpus_size(self):
        return len(self._corpus)
    
    @property
    def corpus(self):
        return self._corpus.copy()
    
    def add_trigram(self, trigram: tuple[int, int, int]):
        self._trigrams.append(trigram)

    def replace_empty_space(self, c: str): 
        return "<SPACE>" if c == " " else c
    
    def __str__(self) -> str:
        return ', '.join(self._corpus)


In [61]:
# Loading Documents and Building the Corpus
# corpora = ''.join(open("different versions of word vectors.txt", encoding="utf-8").read().splitlines())

corpus: TextCorpus | None  
with open("different versions of word vectors.txt", 'r', encoding='utf-8') as document:
    c = document.read()
    corpus = TextCorpus(c)
    

# Need to add the `special characters` for Start and End
for i, (x, y, z) in enumerate(zip(c[:-1], c[1:], c[2:])):
    # print(f"trigram: [{x, y}: {z} -> length Z = {len(z)}]")
    trigram = (corpus.stoi[x], corpus.stoi[y], corpus.stoi[z])
    corpus.add_trigram(trigram)


    # xs = torch.tensor(data)
# ys = torch.tensor(labels)

# print(xs[:20])
# ys[:10]

# xs.shape




AttributeError: 'TextCorpus' object has no attribute '_trigrams'

In [ ]:
one_hot = torch.eye(55)
g = torch.Generator().manual_seed(42)

# W_ = torch.randn((55, 55), generator=g)
W_ = torch.randn((110, 55), generator=g)


flattened_input = one_hot[:2].flatten()
print(f"flattened: {flattened_input}")

result = one_hot[:2].flatten() @ W_
print(result)

# result.shape







tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.])
tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.])
flattened: tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
   

In [113]:
# What if my distribution is not normal (Gaussian)? 
# Run some code to calculate the mean and std deviation from W_
# W_ = torch.randn((55, 1), generator=g)
# print(f"W_ -> {W_[:10]}")

# mean = W_.mean()
# median = W_.median()
# diff = W_ - mean
# sum_squared = ((diff**2).sum()) / 55

# What is the standard deviation?
# R: It is the mean of the sum of the difference between all items from the mean



In [60]:
g = torch.Generator().manual_seed(42)

# W_ = torch.randn((55, 55), generator=g)
W_0 = torch.randn((12, 6), generator=g)
a = torch.tensor([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]).float()
# print(a.shape)
# print(W_0)

# a @ W_0

W = torch.randn((4, 2), generator=g)
W



tensor([[ 1.9199, -0.2254],
        [-0.3417,  0.3040],
        [-0.6890, -1.1267],
        [-0.2858, -1.0935]])