In [58]:
# Imports
import torch
import numpy as np




In [59]:
# Utils


class TextCorpus:

    _corpus: list
    _content: str 
    _trigrams: list[tuple[int, int, int]]

    stoi: dict[str, int] 

    def __init__(self, content: str) -> None:
        if not len(content) >= 3:
            raise ValueError()
        
        self._content = content
        
        self._build_corpus()

        
    def _build_corpus(self):
        self._corpus = sorted(list(set(self._content)))
        self.stoi = { t: i for i, t in enumerate(self._corpus)}

    @property
    def corpus_size(self):
        return len(self._corpus)
    
    @property
    def corpus(self):
        return self._corpus.copy()
    
    def add_trigram(self, trigram: tuple[int, int, int]):
        self._trigrams.append(trigram)

    def replace_empty_space(self, c: str): 
        return "<SPACE>" if c == " " else c
    
    def __str__(self) -> str:
        return ', '.join(self._corpus)


In [ ]:
# Loading Documents and Building the Corpus
# corpora = ''.join(open("different versions of word vectors.txt", encoding="utf-8").read().splitlines())

corpus: TextCorpus | None  
with open("different versions of word vectors.txt", 'r', encoding='utf-8') as document:
    c = document.read()
    corpus = TextCorpus(c)
    

for i, (x, y, z) in enumerate(zip(c[:-1], c[1:], c[2:])):
    # print(f"trigram: [{x, y}: {z} -> length Z = {len(z)}]")
    trigram = (corpus.stoi[x], corpus.stoi[y], corpus.stoi[z])
    corpus.add_trigram(trigram)

    


data = []
labels = []
raw_data = []
raw_labels = []

# size = len(corpora)
# for i, xy in enumerate(zip(corpora[:-1], corpora[1:], corpora[2:])):
#     if i == 0:
#         raw_input = ["<START>", xy[0]]
#         raw_output = xy[1]
#         raw_data.append(raw_input)
#         raw_labels.append(raw_output)

#         xs = [look_up_ctoi[key] for key in map(get_with_special_char, raw_input)]
#         # xs = [look_up_ctoi[get_with_special_char("<START>")], look_up_ctoi[get_with_special_char(xy[0])]]
#         ys = look_up_ctoi[get_with_special_char(raw_output)]
#         data.append(xs)    
#         labels.append(ys)
#     elif i == 1992:
#         raw_input = [xy[1], xy[2]]
#         raw_output = "<END>"
#         raw_data.append(raw_input)
#         raw_labels.append(raw_output)

#         xs = [look_up_ctoi[key] for key in map(get_with_special_char, raw_input)]
#         # xs = [look_up_ctoi[get_with_special_char(xy[1])], look_up_ctoi[get_with_special_char(xy[2])]]
#         ys = look_up_ctoi[get_with_special_char(raw_output)]
#         data.append(xs)    
#         labels.append(ys)
    
#     raw_input = [xy[0], xy[1]]
#     raw_output = xy[2]
#     raw_data.append(raw_input)
#     raw_labels.append(raw_output)

#     xs = [look_up_ctoi[key] for key in map(get_with_special_char, raw_input)]
#     # xs = [look_up_ctoi[get_with_special_char(xy[0])], look_up_ctoi[get_with_special_char(xy[1])]]
#     data.append(xs)
#     ys = look_up_ctoi[get_with_special_char(raw_output)]
#     labels.append(ys)


# print("Raw Data: ", raw_data)
# print("Data: ", data, " => ", len(data))

# print("Raw Labels: ", raw_labels)
# print("Labels: ", labels, " => ", len(labels))

# xs = torch.tensor(data)
# ys = torch.tensor(labels)

# print(xs[:20])
# ys[:10]

# xs.shape





,  , (, ), +, ,, -, ., 0, 2, :, =, ?, A, B, E, F, G, I, L, N, P, S, T, W, X, [, ], a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, ”, −


In [ ]:
one_hot = torch.eye(55)
g = torch.Generator().manual_seed(42)

# W_ = torch.randn((55, 55), generator=g)
W_ = torch.randn((110, 55), generator=g)


flattened_input = one_hot[:2].flatten()
print(f"flattened: {flattened_input}")

result = one_hot[:2].flatten() @ W_
print(result)

# result.shape







tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.])
tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.])
flattened: tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
   

In [113]:
# What if my distribution is not normal (Gaussian)? 
# Run some code to calculate the mean and std deviation from W_
# W_ = torch.randn((55, 1), generator=g)
# print(f"W_ -> {W_[:10]}")

# mean = W_.mean()
# median = W_.median()
# diff = W_ - mean
# sum_squared = ((diff**2).sum()) / 55

# What is the standard deviation?
# R: It is the mean of the sum of the difference between all items from the mean



In [29]:
g = torch.Generator().manual_seed(42)

# W_ = torch.randn((55, 55), generator=g)
W_0 = torch.randn((12, 6), generator=g)
a = torch.tensor([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]).float()
# print(a.shape)
# print(W_0)

# a @ W_0

W = torch.randn((8, 4), generator=g)
W



tensor([[ 0.7281, -0.7106, -0.6021,  0.9604],
        [ 0.4048, -1.3543, -0.4976,  0.4747],
        [-0.1976,  1.2683,  1.2243,  0.0981],
        [ 1.7423, -1.3527,  0.2191,  0.5526],
        [-0.6788,  0.5743,  0.1877, -0.3576],
        [-0.3165,  0.5886, -0.8905,  0.4098],
        [-0.9864,  0.1233,  0.3499,  0.6173],
        [-0.1693,  0.2332,  4.0356,  1.2795]])