In [1]:
# Imports

import torch
import numpy as np



In [ ]:
# Utils
def get_with_special_char(c: str): 
    return "<SPACE>" if c == " " else c

In [ ]:
# Loading corpora
corpora = ''.join(open("any.txt", encoding="utf-8").read().splitlines())
print("corpora: ", corpora)

# Char based model
vocabulary = sorted(set(corpora))

# When it sorts the chars empty space becomes the first one
vocabulary[0] = "<SPACE>"
vocabulary.extend(["<START>", "<END>"])
print("vocabulary: ", vocabulary)

look_up_ctoi = {c: i for i,c in enumerate(vocabulary)}
print(look_up_ctoi)

look_up_itoc = {i: c for c, i in look_up_ctoi.items()}
# print(look_up_itoc)


data = []
labels = []
raw_data = []
raw_labels = []

# size = len(corpora)
for i, xy in enumerate(zip(corpora[:-1], corpora[1:], corpora[2:])):
    if i == 0:
        raw_input = ["<START>", xy[0]]
        raw_output = xy[1]
        raw_data.append(raw_input)
        raw_labels.append(raw_output)

        xs = [look_up_ctoi[key] for key in map(get_with_special_char, raw_input)]
        # xs = [look_up_ctoi[get_with_special_char("<START>")], look_up_ctoi[get_with_special_char(xy[0])]]
        ys = look_up_ctoi[get_with_special_char(raw_output)]
        data.append(xs)    
        labels.append(ys)
    elif i == 1992:
        raw_input = [xy[1], xy[2]]
        raw_output = "<END>"
        raw_data.append(raw_input)
        raw_labels.append(raw_output)

        xs = [look_up_ctoi[key] for key in map(get_with_special_char, raw_input)]
        # xs = [look_up_ctoi[get_with_special_char(xy[1])], look_up_ctoi[get_with_special_char(xy[2])]]
        ys = look_up_ctoi[get_with_special_char(raw_output)]
        data.append(xs)    
        labels.append(ys)
    
    xs = [look_up_ctoi[get_with_special_char(xy[0])], look_up_ctoi[get_with_special_char(xy[1])]]
    data.append(xs)
    ys = look_up_ctoi[get_with_special_char(xy[2])]
    labels.append(ys)

print("Data: ", data, " => ", len(data))
print("Labels: ", labels, " => ", len(labels))

# print(len(data))
# len(labels)

# xs = torch.tensor(data)
# ys = torch.tensor(labels)

# print(xs[:20])
# ys[:10]

# xs.shape




corpora:  To compare the quality of different versions of word vectors, previous papers typically use a tableshowing example words and their most similar words, and understand them intuitively. Althoughit is easy to show that word France is similar to Italy and perhaps some other countries, it is muchmore challenging when subjecting those vectors in a more complex similarity task, as follows. Wefollow previous observation that there can be many different types of similarities between words, forexample, word big is similar to bigger in the same sense that small is similar to smaller. Exampleof another type of relationship can be word pairs big - biggest and small - smallest [20]. We furtherdenote two pairs of words with the same relationship as a question, as we can ask: ”What is theword that is similar to small in the same sense as biggest is similar to big?”Somewhat surprisingly, these questions can be answered by performing simple algebraic operationswith the vector representation of

In [ ]:
one_hot = torch.eye(55)
g = torch.Generator().manual_seed(42)

# W_ = torch.randn((55, 55), generator=g)
W_ = torch.randn((110, 55), generator=g)


flattened_input = one_hot[:2].flatten()
print(f"flattened: {flattened_input}")

result = one_hot[:2].flatten() @ W_
print(result)

# result.shape







tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.])
tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.])
flattened: tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
   

In [113]:
# What if my distribution is not normal (Gaussian)? 
# Run some code to calculate the mean and std deviation from W_
# W_ = torch.randn((55, 1), generator=g)
# print(f"W_ -> {W_[:10]}")

# mean = W_.mean()
# median = W_.median()
# diff = W_ - mean
# sum_squared = ((diff**2).sum()) / 55

# What is the standard deviation?
# R: It is the mean of the sum of the difference between all items from the mean



In [11]:
g = torch.Generator().manual_seed(42)

# W_ = torch.randn((55, 55), generator=g)
W_0 = torch.randn((12, 6), generator=g)
a = torch.tensor([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]).float()
print(a.shape)
print(W_0)

a @ W_0



torch.Size([12])
tensor([[ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784, -1.2345],
        [-0.0431, -1.6047, -0.7521,  1.6487, -0.3925, -1.4036],
        [-0.7279, -0.5594, -0.7688,  0.7624,  1.6423, -0.1596],
        [-0.4974,  0.4396, -0.7581,  1.0783,  0.8008,  1.6806],
        [ 1.2791,  1.2964,  0.6105,  1.3347, -0.2316,  0.0418],
        [-0.2516,  0.8599, -1.3847, -0.8712, -0.2234,  1.7174],
        [ 0.3189, -0.4245,  0.3057, -0.7746, -1.5576,  0.9956],
        [-0.8798, -0.6011, -1.2742,  2.1228, -1.2347, -0.4879],
        [-0.9138, -0.6581,  0.0780,  0.5258, -0.4880,  1.1914],
        [-0.8140, -0.7360,  0.1453,  0.2311,  0.0087, -0.1423],
        [ 0.1971, -1.1441,  0.3383,  1.6992,  2.8140,  0.3598],
        [-0.0898,  0.4584, -0.5644,  1.0563, -1.4692,  1.4332]])


tensor([ 1.0471,  0.8861, -0.3734,  0.0173, -0.5562, -1.7225])